# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/msg/analog_array.msg;/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/msg/SSCMove.msg;/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/msg/SSCMoveList.msg;/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/msg/FileList.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/RecordAction.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/RecordActionGoal.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/RecordActionResult.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/RecordActionFeedback.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/RecordGoal.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/RecordResult.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/RecordFeedback.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/PlaybackAction.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/PlaybackActionGoal.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/PlaybackActionResult.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/PlaybackActionFeedback.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/PlaybackGoal.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/PlaybackResult.msg;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg/PlaybackFeedback.msg"
services_str = "/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/srv/Files.srv;/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/srv/Serials.srv;/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/srv/SSCMoveCommand.srv"
pkg_name = "pumpkin_messages"
dependencies_str = "std_msgs;actionlib_msgs"
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "pumpkin_messages;/home/rafaelpaiva/workspace/pumpkin_ws/src/pumpkin_messages/msg;pumpkin_messages;/home/rafaelpaiva/workspace/pumpkin_ws/build-src-Desktop-Default/devel/share/pumpkin_messages/msg;std_msgs;/opt/ros/indigo/share/std_msgs/cmake/../msg;actionlib_msgs;/opt/ros/indigo/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/indigo/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
