#List of joint positions that identify the initial and the final state of the robot
#These positions are ordered by the Arduino PIN
float64[] initial_positions
float64[] final_positions
---
#The planned trajectory
#We just get the joint_trajectory
trajectory_msgs/JointTrajectory[] joint_trajectory
