set(_CATKIN_CURRENT_PACKAGE "analog_read")
set(analog_read_MAINTAINER "thiago <thiago@todo.todo>")
set(analog_read_DEPRECATED "")
set(analog_read_VERSION "0.0.0")
set(analog_read_BUILD_DEPENDS "std_msgs" "message_generation")
set(analog_read_RUN_DEPENDS "std_msgs" "message_runtime")
set(analog_read_BUILDTOOL_DEPENDS "catkin")